### ISSUE TITLE
FMOD cannot build banks while Godot editor is open

### ISSUE THREAD

**Issue by NumbuhFour** [alessandrofama/fmod-for-godot#10]
### FMOD for Godot version

fmod-20214-for-godot-4.1-stable-1.0-alpha-2

### System information

Windows 10

### Issue description

Godot Version: v4.1.1.stable.official [bd6af8e0e], compatibility mode

After setting up FMOD plugin in Godot and confirming banks load events can play, attempting to build banks from the FMOD editor fails:

![image](https://github.com/alessandrofama/fmod-for-godot/assets/6756611/71c753b3-8862-4706-b13a-0bd5a12c0347)

This effectively means the Godot editor must be closed every time changes in FMOD have been made. This severely hampers development as time between even small iterations is significant.

I have tried several things to prevent this and narrow down what might be causing it. So far, all of the following produces the same above error:
 - Restart the Godot Editor. Attempt to build before doing anything in godot (before playing or refreshing fmod or anything)
 - Do not load banks at startup, only via `StudioBankLoader` node set to `Load On: Ready`
 - Disable Live Updating
 - Create and run a tool script to call `unload` on `StudioBankLoader`
 - Create and run a tool script to call `FMODStudioModule.shutdown`
   - I also tried `FMODStudioEditorModule.shutdown` and both together
 - Disable the FMOD integration plugin

So the only thing I've been able to conclude is that banks seem to get locked as soon as the editor starts up, and will not be released until the editor shuts down no matter what settings are changed or code is executed.
One thing of note is that the banks only get locked after the _first Refresh Project_ is performed in the plugin. But after that, the banks are locked every time the editor is opened for the lifetime of the application.

FMOD's verbose log while trying to build and failing:
```
18:57:53 Macro: Build Started Sript Action 
18:57:53 [Build 1 banks for 1 platforms]: Time started 
18:57:53 [Gather file stats in X:/Projects/_DProjects/godot/Legend of the Landscaper/FMOD/LandscaperFMOD/Assets]: Time started 
18:57:53 [Gather file stats in X:/Projects/_DProjects/godot/Legend of the Landscaper/FMOD/LandscaperFMOD/Assets]: Time taken is 0.13ms (0.000s) 
18:57:53 [Build bank "Master"]: Time started 
18:57:53 [Write X:/Projects/_DProjects/godot/Legend of the Landscaper/FMOD/LandscaperFMOD/Build/Desktop/Master.bank to file]: Time started 
18:57:53 "FMOD_ERROR (13): Error loading file." 
18:57:53 "FMOD_ERROR c:\\buildagent3\\work\\b8b6893b00c565e4\\studio\\src\\model\\bank.cpp(135): stream.open()" 
18:57:53 [Write X:/Projects/_DProjects/godot/Legend of the Landscaper/FMOD/LandscaperFMOD/Build/Desktop/Master.bank to file]: Time taken is 0.29ms (0.000s) 
18:57:53 "FMOD_ERROR (13): Error loading file." 
18:57:53 "FMOD_ERROR c:\\buildagent3\\work\\b8b6893b00c565e4\\studio\\src\\model\\bank.cpp(150): buildBank(this, dataType, absoluteBinaryPath(platform, locale, sBankSuffix(dataType)))" 
18:57:53 [Build bank "Master"]: Time taken is 5.46ms (0.005s) 
18:57:58 [Build 1 banks for 1 platforms]: Time taken is 4535.53ms (4.535s) 
18:57:58 Macro: Build Ended Script Action 
```

### Steps to reproduce

1. Create and open a new Godot project
2. Copy the `addons` folder from the plugin's zip into the project folder
3. In Project Settings > Plugins, enable the FMOD plugin
4. Close the Godot editor
5. Reopen the Godot project
6. Create and open a new FMOD Studio project
7. Create a test event in FMOD and assign it to the Master bank
9. Save the FMOD project to the root folder of the Godot project
10. Build banks
11. In Godot's Project Settings, enable Advanced Settings
12. In Godot's FMOD settings, set the Banks folder to `*FMODProjectName*/Build/Desktop`
13. Close the Godot settings
14. Open the FMOD plugin window with the button in the top right
15. Click `Refresh Project`
16. In FMOD Studio, attempt to build banks

Expected: Banks can be built without error
Result: FMOD is prevented from building banks

### Minimal reproduction project

[GDrive Download](https://drive.google.com/file/d/1TUHLx87_Vim91zsmXZpc-9IXS6uePtjo/view?usp=drive_link)
Zip includes addons folder just for sanity

**Comment by NumbuhFour** [comment]
I have found a _slight_ workaround. With some heavy caveats.

Since I only ever need to refresh banks when I add new events, I made a bunch of placeholder events for everything I _think_ I need in advance, and refreshed FMOD in godot.

Then, in `addons/FMOD/editor/editor_addon.gd` I commented out lines 33-37
```gdscript
	# if !FMODStudioEditorModule.is_connected("banks_loading", Callable(self, "on_banks_loading")):
	#	FMODStudioEditorModule.connect("banks_loading", Callable(self, "on_banks_loading"))

	# Load all banks
	# FMODStudioEditorModule.load_all_banks()
```

Now FMOD is able to build banks with the editor open. This allows me to make changes to my events, build banks, then test them in-game. This, however, prevents refreshing the FMOD project and therefore prevents loading new events.

To add new events (or banks) I just uncomment those lines, restart the editor, then hit the Refresh FMOD project button to load them in. And afterwards comment it out and restart the editor again. The restarts are needed to force the editor to release the banks files.

It's a cumbersome workflow, but thankfully I don't need to make new events often.

**Comment by alessandrofama** [comment]
Fixed by https://github.com/alessandrofama/fmod-for-godot/pull/12.
