### ISSUE TITLE
Support git tags for package manager

### ISSUE THREAD

**Issue by Creta5164** [alessandrofama/fmod-for-godot#16]
### FMOD for Godot version

1.0-alpha3_fmod20214_godot4.1

### System information

Windows 11

### Issue description

When I first tried to install this package without thinking, I tried to install it through Chickensoft's Chicken (it named GodotEnv nowdays) package manager.

https://github.com/chickensoft-games/GodotEnv#-addon-management

However, it failed because the remote repository didn't have any native libraries built.

I've set up the package registration as shown below.

![image](https://github.com/alessandrofama/fmod-for-godot/assets/13521406/846da07f-57e2-4a9b-915c-eb0286b8090b)

The reason for using a package manager is to strongly tie the project to the version it uses and to ensure that the packages it depends on work.  
(Nuget, NPM, etc.)

It would be nice to have a tag that holds the separately built deliverables for this.

### Steps to reproduce

1. Start Godot with .NET build
2. open project directory and launch terminal
3. Follow instructions from [GodotEnv](https://github.com/chickensoft-games/GodotEnv#-installation)
4. Take [addon management instructions](https://github.com/chickensoft-games/GodotEnv#-addon-management)
5. After running `godotenv addons init` in terminal to create `addons.jsonc`, setup content like below.
```jsonc
{
  "$schema": "https://chickensoft.games/schemas/addons.schema.json",
  "addons": {
    "FMOD": {
        "url": "https://github.com/alessandrofama/fmod-for-godot.git",
        "source": "remote",
        "checkout": "1.0-alpha3_fmod20214_godot4.1",
        "subfolder": "addons/FMOD"
    }
  }
}
```
6. type `godotenv addons install` to install `FMOD` package from this repo.
7. It takes pure repo content from origin.

### Minimal reproduction project

[FMOD.zip](https://github.com/alessandrofama/fmod-for-godot/files/12642977/FMOD.zip)

1. Extract ZIP
2. Run `terminal-commands.bat` (Make sure .NET SDK installed)

Note : You can uninstall tool with `dotnet tool uninstall --global Chickensoft.GodotEnv`

**Comment by alessandrofama** [comment]
I have reservations about adding the libraries to the repository as it would substantially increase the size of the repository. What do you think?

**Comment by Creta5164** [comment]
Yes, indeed, writing an 80MB file is certainly worrying about the size and capacity of the repository history.
It's regrettable that there's no package host service yet in Godot, but I've often seen similar Unity open-source developers primarily hosting package versions in the same repository.
So I was tried to install it in the same way but failed, because (of course) the repository does not promote the role of package hosting.

Would it be too much to put it in a separate branch or directory?

If it seems too difficult, I'll to request a feature that allows GodotEnv to receive Release content.

**Comment by alessandrofama** [comment]
Yeah, the extracted libraries amount to about 300MB in total. In its current state, the repository isn't really intended to be directly cloned into a Godot project. In the released archive, not only are the libraries included, but a general cleanup is performed at the CI stage (removing source and test project) and the Android plugin is added.

I’m sorry that I cannot fulfill your request at this stage. Additionally, I do not support C# at the moment. Is it even possible to use this integration with C#? Another potential solution could involve hosting the libraries on a separate repository, but I can't justify dedicating time to that right now.

**Comment by Creta5164** [comment]
I see, seems this issue should belong to GodotEnv to make it support fetch from release with tags.
GodotEnv is made in dotnet tools but it does work generally, not only C#.

As I know there's another package manager that made with only GDScript too, seems also I should poke this one too.  
https://github.com/imjp94/gd-plug

> Additionally, I do not support C# at the moment. Is it even possible to use this integration with C#?

As I know that Godot's C# API supports invoke GDScript methods(like `Variant.Call`), I saw that someone made codegen C# class for gluing it's GDScript boxed area.  
https://godotengine.org/asset-library/asset/1766

Guess I'll follow that way to use it, thanks to your great work anyways!

I'll close this issue, may I mention this to package manager repo later.
