### ISSUE TITLE
StudioSystem.get_bus_by_id fails without explicitly waiting before calling it

### ISSUE THREAD

**Issue by tapir2342** [alessandrofama/fmod-for-godot#19]
### FMOD for Godot version

1.0

### System information

Windows 11

### Issue description

Hi, calling `StudioSystem.get_bus_by_id` with a valid ID fails for me. I have made sure to close/re-open godot, export the FMOD project, refresh it, and regerate the IDs (they haven't changed because I didn't change anything in the FMOD project itself). Only the `modified_time` field in the `BankAsset`s resource have been updated.

Am I using this wrong? I expected `StudioSystem` to be ready to use as soon as StudioSystem.is_valid()` returns `true`. But maybe that's wrong?

Thank you.

### Steps to reproduce

When I call `StudioSystem.get_bus_by_id` immediately without waiting, the Bus cannot be found. If I wait *some time*, it works.

**Not working:**

```gdscript
assert(StudioSystem.is_valid()) # true
var bus := StudioSystem.get_bus_by_id(FMODGuids.Busses.MASTER_BUS)
assert(bus.is_valid()) # false
```

**Working:**

```gdscript
assert(StudioSystem.is_valid()) # true
await get_tree().create_timer(1.0).timeout
var bus := StudioSystem.get_bus_by_id(FMODGuids.Busses.MASTER_BUS)
assert(bus.is_valid()) # true
```

### Minimal reproduction project

Providing this is currently not possible, because it would be hard to re-recreate my project exactly. I'd rather take the time to look into the actual source code to help with finding the bug. Thanks for understanding.

**Comment by alessandrofama** [comment]
While having a valid `StudioSystem`, it's important to note that the availability of any specific bus is not guaranteed. The Master bus, for instance, becomes accessible only after the successful loading of the Master bank. I've conducted some testing, and the results are as follows:

When loading the master bank synchronously (blocking fashion), the bus becomes available:

```gdscript
func _ready():
	var studio_system = FMODStudioModule.get_studio_system()
	var bank = studio_system.load_bank_file("res://banks/Desktop/Master.bank", FMODStudioModule.FMOD_STUDIO_LOAD_BANK_NORMAL, false)
	var bus = studio_system.get_bus_by_id(FMODGuids.Busses.MASTER_BUS)
	print(bus.is_valid()) # true
```

However, when loading the master bank asynchronously, the bus remains unavailable:

```gdscript
func _ready():
	var studio_system = FMODStudioModule.get_studio_system()
	var bank = studio_system.load_bank_file("res://banks/Desktop/Master.bank", FMODStudioModule.FMOD_STUDIO_LOAD_BANK_NONBLOCKING, false)
	var bus = studio_system.get_studio_system().get_bus_by_id(FMODGuids.Busses.MASTER_BUS)
	print(bus.is_valid()) # false
```

To confirm this behavior, you can check the loading state of the bank and ensure it reaches the 'Loaded' state before accessing the bus:

```gdscript
func _ready():
	var studio_system = FMODStudioModule.get_studio_system()
	var bank = studio_system.load_bank_file("res://banks/Desktop/Master.bank", FMODStudioModule.FMOD_STUDIO_LOAD_BANK_NONBLOCKING, false)
	var loading_state = FMODStudioModule.FMOD_STUDIO_LOADING_STATE_UNLOADED
	while loading_state != FMODStudioModule.FMOD_STUDIO_LOADING_STATE_LOADED:
		loading_state = bank.get_loading_state()
		if loading_state == FMODStudioModule.FMOD_STUDIO_LOADING_STATE_ERROR:
			break
		await get_tree().process_frame
	var bus = studio_system.get_bus_by_id(FMODGuids.Busses.MASTER_BUS)
	print(bus.is_valid()) # true
```

I hope this clarifies the behavior for you. Does it answers your question?

**Comment by tapir2342** [comment]
Hi @alessandrofama, thanks a lot for your response and the explanation!
I was just about to write a reply, because I was using it wrong. I indeed wasn't loading the bank properly before trying to access the busses. This is the first time I'm using FMOD, so I wasn't fully aware how these two are related.

Sorry if I caused you effort.

**Comment by alessandrofama** [comment]
No worries, feel free to open additional issues if you encounter new problems. You can also join the Discord if you like. Cheers.
