### ISSUE TITLE
Can‘t find all the Fmod modules reference when running on exported windows client with debug

### ISSUE THREAD

**Issue by MadFlyFish** [alessandrofama/fmod-for-godot#2]
![image](https://user-images.githubusercontent.com/36298330/224495628-485f732d-d46d-404a-b0ad-5b1b3c2aa6ac.png)

### However, it runs well when exported with release, or in the godot editor mode.

**Comment by alessandrofama** [comment]
It seems like it can't load the debug version of the GDExtension library and therefore won't find the types defined in there.
From my experience this happens on Windows when you are missing the debug version of the Visual C++ Redistributable.

Can you open the debug GDExtension .dll (libfmod.windows.template_debug.dll) with a dependency walker (https://lucasg.github.io/Dependencies/) and check which dependencies are missing on your pc?

Can you verify that you have the MSVC C++-x64/x86-Buildtools installed? You can find them as a package in the Visual Studio Installer. For example the ``MSVC v143 – VS 2022 C++ x64/x86-Build Tools``. Usually installing these will solve this issue. Let me know if it works out.

**Comment by MadFlyFish** [comment]
It seems that the ucutbased.dll is missing?
![image](https://user-images.githubusercontent.com/36298330/224520332-5d5bdc70-eb80-4010-985f-ebebc47418c0.png)

**Comment by alessandrofama** [comment]
Yep, `ucrtbased.dll" is missing. Can you try to install the Windows SDK from Visual Studio?

**Comment by MadFlyFish** [comment]
### **Problem solved by installing Windows SDK and MSVC C++-x64/x86-Buildtools . Thanks.**
![image](https://user-images.githubusercontent.com/36298330/224602202-db7a5d3f-01c8-4898-9ca0-5d02657b7669.png)
![image](https://user-images.githubusercontent.com/36298330/224602541-e6cb85e1-e02e-4db3-a1ee-c33faeb04258.png)
