### ISSUE TITLE
Audio not played in export

### ISSUE THREAD

**Issue by DevMimas** [alessandrofama/fmod-for-godot#22]
### FMOD for Godot version

FMOD 2.02.17 for Godot 4.1.1 stable v1.0-alpha-4

### System information

Windows 10

### Issue description

In playmode in the editor, the audio is played. Without the StudioBankLoader and so on. Everything by code.
But the audio is not played on export and there are warnings that the banks were not found.
Currently only tested with Windwos 10.

**Godot Version**
Godot v4.1.1.stable.mono.official [bd6af8e0e]

I use the C# version because I want to write the game in it. But for Fmod there is currently only a GDScript plugin. Both languages are allowed in Godot at the same time according to the documentation.

## Code example
**Load banks in MainScene**
```py
extends Node2D

@export var bank_asset_master: BankAsset
@export var bank_asset_mstring: BankAsset
@export var bank_asset_ui: BankAsset

func _enter_tree() -> void:
	FMODStudioModule.get_studio_system().load_bank_file(bank_asset_master.file_path, FMODStudioModule.FMOD_STUDIO_LOAD_BANK_NORMAL, false)
	FMODStudioModule.get_studio_system().load_bank_file(bank_asset_mstring.file_path, FMODStudioModule.FMOD_STUDIO_LOAD_BANK_NORMAL, false)
	FMODStudioModule.get_studio_system().load_bank_file(bank_asset_ui.file_path, FMODStudioModule.FMOD_STUDIO_LOAD_BANK_NORMAL, false)
	print("File Path: " + bank_asset_master.file_path)
	print("File Path: " + bank_asset_mstring.file_path)
	print("File Path: " + bank_asset_ui.file_path)
```

**Code to start audio in second scene**
```py
extends Node2D

@export var event: Array[String]
var instance: EventInstance
var index: int

func _ready():
	index = 0
	instance = FMODRuntime.create_instance_path(event[0])
	print("Instance: " + event[0])

func _on_audio_start_pressed():
	instance.start()

func _on_audio_stop_pressed():
	instance.stop(FMODStudioModule.FMOD_STUDIO_STOP_ALLOWFADEOUT)

func _on_tree_exited():
	instance.stop(FMODStudioModule.FMOD_STUDIO_STOP_IMMEDIATE)
	instance.release()

func _on_next_sound_pressed():
	index += 1
	if index == 0:
		instance.stop(FMODStudioModule.FMOD_STUDIO_STOP_IMMEDIATE)
		instance.release()
		instance = FMODRuntime.create_instance_path(event[index])
		print("Sound: " + event[index])
	elif index == 1:
		instance.stop(FMODStudioModule.FMOD_STUDIO_STOP_IMMEDIATE)
		instance.release()
		instance = FMODRuntime.create_instance_path(event[index])
		index = -1
		print("Sound: " + event[index])
```

## Export Console
Picture from export console with warnings. Bank files not found
![grafik](https://github.com/alessandrofama/fmod-for-godot/assets/44207756/2501b346-c2f2-4310-9974-642a7192f2f1)

### Steps to reproduce

1. Create new project
2. Create Scene
3. Set up plugin
4. Play audio by code
5. Export project for Windows

### Minimal reproduction project

I can submit it later.

**Comment by alessandrofama** [comment]
Have you added ``*.bank`` filter to the ``Filters to export non-resource files/folders`` setting in the Resources tab of the export window?

![](https://alessandrofama.com/wp-content/uploads/sites/3/fmod_godot_export_window.png)

**Comment by DevMimas** [comment]
Thanks a lot! It worked with it. Unfortunately, I somehow missed that in the tutorial. 
Maybe you want to define that in the readme a bit more.

Thanks for your great work and hopefully more great updates will follow 🙂

**Comment by alessandrofama** [comment]
I’ll add this more prominently in the tutorials. Cheers
