### ISSUE TITLE
Feature request: quick playback of events from the editor

### ISSUE THREAD

**Issue by starry-abyss** [alessandrofama/fmod-for-godot#25]
### FMOD for Godot version

built from source

### System information

Ventura 13.5.2

### Issue description

Hey, I'm working on a game with FMOD. Sound designers sent me the banks with many new sounds, and I don't know e.g. which of the events are looped or not until I write some code to play them.

Would be cool to play the sounds available in the banks right in the Godot editor. For example, in that menu with the list of all events (not only events) where their paths can be copied.

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by alessandrofama** [comment]
You can already playback events in the browser (icon at top right of godot). Does that work for you?
![image](https://github.com/alessandrofama/fmod-for-godot/assets/26153311/340efd04-a538-419e-a71b-7c3b3e0eacaf)

**Comment by starry-abyss** [comment]
Looks good, but on my laptop also I can't reach the bottom of FMOD Project Browser because it's taller than my monitor's resolution... And I don't know any way to make it shorter.

Is this the reason why I don't see Play Event? Or did you add it later? The version I used for the jam doesn't have the right column with Parameters Preview.

**Comment by alessandrofama** [comment]
> Looks good, but on my laptop also I can't reach the bottom of FMOD Project Browser because it's taller than my monitor's resolution... And I don't know any way to make it shorter.
> 
> Is this the reason why I don't see Play Event? Or did you add it later? The version I used for the jam doesn't have the right column with Parameters Preview.

I think this issue was fixed but haven't release a new version of the plugin. Maybe you could try to use a new build and check if it is fixed? https://github.com/alessandrofama/fmod-for-godot/actions/runs/7560565056/artifacts/1176258074
