### ISSUE TITLE
Audio latency on Windows 11

### ISSUE THREAD

**Issue by jefvel** [alessandrofama/fmod-for-godot#26]
### FMOD for Godot version

FMOD 2.02.17 for Godot 4.1.1 stable v1.0-alpha-4

### System information

Windows 11

### Issue description

There's significant latency when I'm running a it on Windows. I've tried to solve it by lowering the audio buffer size and changing settings, but it doesn't seem to help. The latency is still there if I create a `EventInstance` beforehand and start it.

Here's a video , the pitched down sound is Godot's AudioStreamPlayer.
https://streamable.com/4fitti

### Steps to reproduce

Create a node with a `EventAsset`, and a `AudioStreamPlayer` that has the same sound (I just use a click sound). Pitch that one up or down.

Play both the FMOD event and the `AudioStreamlayer` when clicking/pressing a key. The `AudioStreamPlayer` will play about 100-200 ms before FMOD.

### Minimal reproduction project

I omitted the addon files so they need to be added, and the sound event has to be added to the node.
Press space to play the sounds

[fmodlatency.zip](https://github.com/alessandrofama/fmod-for-godot/files/13467218/fmodlatency.zip)

**Comment by alessandrofama** [comment]
I'm closing this issue as I won't be able to work on this anymore.
