### ISSUE TITLE
Web build for Godot 4.2

### ISSUE THREAD

**Issue by IntangibleMatter** [alessandrofama/fmod-for-godot#28]
### FMOD for Godot version

n/a

### System information

Web

### Issue description

As of Godot 4.2 (released today) GDExtension can *finally* be built for web. It would be *awesome* to be able to use this with the Web build of Godot, allowing much more advanced and dynamic audio in the browser

### Steps to reproduce

n/a

### Minimal reproduction project

n/a

**Comment by alessandrofama** [comment]
GDExtensions can be built for the web, but when trying to link with the FMOD libs you still get errors as of today. Until these errors are resolved it won't be possible to use FMOD on the web. 
See: 
https://qa.fmod.com/t/issues-with-compiling-for-html5-using-emscripten/17013
https://qa.fmod.com/t/emscripten-link-errors/20127/5
