### ISSUE TITLE
Official Wiki

### ISSUE THREAD

**Issue by nargacu83** [alessandrofama/fmod-for-godot#29]
### FMOD for Godot version

not needed

### System information

not needed

### Issue description

It would be great to create and convert your tutorials from [FMOD + Godot Tutorials](https://alessandrofama.com/tutorials/fmod/godot/) into a wiki on this repository.

This would make the documentation editable by anyone contributing to the project and prevent any loss of data if your website goes down for any reason.

### Steps to reproduce

not needed

### Minimal reproduction project

not needed

**Comment by alessandrofama** [comment]
Unfortunately I never got to bring the docs from my website to the wiki here. I'm closing this issue as I won't have time to do that in the future.
