### ISSUE TITLE
function [RuntimeManager.play_one_shot_path()] does't work

### ISSUE THREAD

**Issue by MadFlyFish** [alessandrofama/fmod-for-godot#3]
![image](https://user-images.githubusercontent.com/36298330/224497103-0acccf6e-196d-43da-9a5b-d26c1cd98767.png)
![image](https://user-images.githubusercontent.com/36298330/224497125-0a5f9d28-742b-4fb6-80ac-276fe5efe422.png)
![image](https://user-images.githubusercontent.com/36298330/224497135-8dcc1b74-7280-43df-91f7-6453d224e7af.png)

### However, RuntimeManager.play_one_shot(event) works well.

**Comment by alessandrofama** [comment]
Do you have the ``.strings`` version of the Master bank loaded? This is required for paths to work in general.

**Comment by MadFlyFish** [comment]
> Do you have the `.strings` version of the Master bank loaded? This is required for paths to work in general.

 Problem solved by loading the .string.bank.
Thanks for your help.
I suggest adding some guideline in the tutorials.

**Comment by alessandrofama** [comment]
I've added this information to https://alessandrofama.com/tutorials/fmod/godot/events.
Thank you!
