### ISSUE TITLE
Naming GUIDs

### ISSUE THREAD

**Issue by Learus** [alessandrofama/fmod-for-godot#31]
### FMOD for Godot version

fmod-20217-for-godot-4.1.1-stable-1.0-alpha-4

### System information

Windows 11

### Issue description

Hi there!

I wanted to propose a small improvement in the naming of the GUID classes.
Specifically, I have an autoload node called `Events` that handles application-wide signals and other things.

Upgrading to 4.2, gave me a conflict with the library's `Events` class.

Thinking long-term and given that the name "Events" or any other name for that matter (Busses, Banks, etc) could conflict with user classes, it might be beneficial to use more specific names.
Those names could just include an `FMOD_` prefix (FMOD_Events) or sth similar.

I have already made this simple change on my project so I can continue working, and it does not seem to cause any issues. If what I'm proposing does not have any unwanted consequences I'm not aware of I'm totally down to do a PR that resolves the issue.

### Steps to reproduce

1. Use Godot 4.2 (not sure if it matters)
2. Create a custom class called `Events` (or `Busses`, `Banks`) and autoload it
3. Tada! Compilation error

### Minimal reproduction project

Pretty simple reproduction. No need to upload project.

**Comment by alessandrofama** [comment]
I'm closing this issue since I won't be able to work on this project. This is a good suggestion though!
