### ISSUE TITLE
The size of fmod project browser is too big.

### ISSUE THREAD

**Issue by MadFlyFish** [alessandrofama/fmod-for-godot#4]
As a result, some buttons cannot be clicked. 
![image](https://user-images.githubusercontent.com/36298330/224636123-486583ba-fc21-4ba4-8798-2439ab13a6c5.png)

**Comment by alessandrofama** [comment]
Can you please add more information as the display resolution and the editor scale (you can find it in the editor settings) you are using? Otherwise I won’t be able to reproduce this.

**Comment by MadFlyFish** [comment]
> Can you please add more information as the display resolution and the editor scale (you can find it in the editor settings) you are using? Otherwise I won’t be able to reproduce this.

Main Screen 1920 x 1080, Second Screen 1080 x 1920
Scale default x1.0
![image](https://user-images.githubusercontent.com/36298330/224640447-3b8e2d6b-b950-4b04-bc42-4611a7246126.png)

**Comment by alessandrofama** [comment]
Can you try the latest version of the integration: https://github.com/alessandrofama/fmod-for-godot/suites/11562950853/artifacts/598840294 ?
It should be better now.

**Comment by MadFlyFish** [comment]
> Can you try the latest version of the integration: https://github.com/alessandrofama/fmod-for-godot/suites/11562950853/artifacts/598840294 ? It should be better now.

Thanks. Could you please provide a compiled version for testing? I'm not familiar with c++ .
^_^
