### ISSUE TITLE
Co-ordinate system is inconsistent in 3D

### ISSUE THREAD

**Issue by surfacedfox** [alessandrofama/fmod-for-godot#5]
### Godot version

4.0.stable

### FMOD version

2.02.12

### System information

Windows 10

### Issue description

The coordinates between Godot and FMOD seem to be inconsistent, causing the sound to come out of the wrong headphone ears  and in opposite attenuation directions(yes, I did double check that I was wearing my headphones right.)

### Steps to reproduce

- Play the Main scene in the project. The audio seems to be coming out of the wrong ears.
- Delete the camera object from the scene. Add the camera_fixed object into the scene from the filesystem tab. The audio seems to be working fine now.
- Note the difference in the transform values of the StudioListener3D between the two cameras. Default has everything set to 0, while the Fixed camera has its rotation as (0,180,0), and scale as (-1,0,0)

### Minimal reproduction project

https://github.com/surfacedfox/Godot-FMOD-coordinates

**Comment by alessandrofama** [comment]
Can you check if the latest ci build fixes your issue? https://github.com/alessandrofama/fmod-for-godot/suites/11652133272/artifacts/605200242

**Comment by surfacedfox** [comment]
Yup, works as intended. Thank you for resolving it quickly, you're the best!
