### ISSUE TITLE
Fmod Project Manager fails to detect the event path changes in the Fmod Studio

### ISSUE THREAD

**Issue by MadFlyFish** [alessandrofama/fmod-for-godot#6]
### FMOD for Godot version

FMOD 2.02.14 for Godot 4.0.2 stable v1.0-alpha-2

### System information

Win11

### Issue description

When an event's path is changed in Fmod Studio, Fmod Project Manager will not detect it.
Refreshing project can't solve the problem,
![image](https://github.com/alessandrofama/fmod-for-godot/assets/36298330/7a6aa2e2-b08f-4c63-a114-41a33a9a7a2d)
![image](https://github.com/alessandrofama/fmod-for-godot/assets/36298330/03db7033-f225-4c49-8bfb-8e65d29553c6)

**Comment by alessandrofama** [comment]
Fixed in #20.
